BEGIN TRANSACTION;
CREATE TABLE categories (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
INSERT INTO "categories" VALUES('تاريخ','تاريخ',1);
INSERT INTO "categories" VALUES('تنمية-بشرية','تنمية بشرية',1);
INSERT INTO "categories" VALUES('روايات','روايات',1);
INSERT INTO "categories" VALUES('علوم','علوم',1);
CREATE TABLE delivery_fees (
    region_number INTEGER PRIMARY KEY,
    region_name TEXT NOT NULL,
    domicile_fee INTEGER NOT NULL CHECK (domicile_fee >= 0),
    stop_desk_fee INTEGER NOT NULL CHECK (stop_desk_fee >= 0)
);
INSERT INTO "delivery_fees" VALUES(1,'أدرار',1400,1100);
INSERT INTO "delivery_fees" VALUES(2,'الشلف',850,500);
INSERT INTO "delivery_fees" VALUES(3,'الأغواط',850,450);
INSERT INTO "delivery_fees" VALUES(4,'أم البواقي',850,500);
INSERT INTO "delivery_fees" VALUES(5,'باتنة',850,500);
INSERT INTO "delivery_fees" VALUES(6,'بجاية',850,500);
INSERT INTO "delivery_fees" VALUES(7,'بسكرة',950,600);
INSERT INTO "delivery_fees" VALUES(8,'بشار',1400,1100);
INSERT INTO "delivery_fees" VALUES(9,'البليدة',850,500);
INSERT INTO "delivery_fees" VALUES(10,'البويرة',850,500);
INSERT INTO "delivery_fees" VALUES(11,'تمنراست',1800,1400);
INSERT INTO "delivery_fees" VALUES(12,'تبسة',950,600);
INSERT INTO "delivery_fees" VALUES(13,'تلمسان',850,500);
INSERT INTO "delivery_fees" VALUES(14,'تيارت',850,500);
INSERT INTO "delivery_fees" VALUES(15,'تيزي وزو',850,500);
INSERT INTO "delivery_fees" VALUES(16,'الجزائر',850,450);
INSERT INTO "delivery_fees" VALUES(17,'الجلفة',850,500);
INSERT INTO "delivery_fees" VALUES(18,'جيجل',850,500);
INSERT INTO "delivery_fees" VALUES(19,'سطيف',850,500);
INSERT INTO "delivery_fees" VALUES(20,'سعيدة',900,600);
INSERT INTO "delivery_fees" VALUES(21,'سكيكدة',850,500);
INSERT INTO "delivery_fees" VALUES(22,'سيدي بلعباس',850,500);
INSERT INTO "delivery_fees" VALUES(23,'عنابة',850,500);
INSERT INTO "delivery_fees" VALUES(24,'قالمة',850,600);
INSERT INTO "delivery_fees" VALUES(25,'قسنطينة',850,500);
INSERT INTO "delivery_fees" VALUES(26,'المدية',850,500);
INSERT INTO "delivery_fees" VALUES(27,'مستغانم',850,500);
INSERT INTO "delivery_fees" VALUES(28,'المسيلة',850,500);
INSERT INTO "delivery_fees" VALUES(29,'معسكر',900,600);
INSERT INTO "delivery_fees" VALUES(30,'ورقلة',1100,800);
INSERT INTO "delivery_fees" VALUES(31,'وهران',850,500);
INSERT INTO "delivery_fees" VALUES(32,'البيض',1100,800);
INSERT INTO "delivery_fees" VALUES(33,'إيليزي',2200,1700);
INSERT INTO "delivery_fees" VALUES(34,'برج بوعريريج',850,500);
INSERT INTO "delivery_fees" VALUES(35,'بومرداس',850,500);
INSERT INTO "delivery_fees" VALUES(36,'الطارف',950,600);
INSERT INTO "delivery_fees" VALUES(37,'تندوف',1800,1400);
INSERT INTO "delivery_fees" VALUES(38,'تيسمسيلت',850,500);
INSERT INTO "delivery_fees" VALUES(39,'الوادي',1100,800);
INSERT INTO "delivery_fees" VALUES(40,'خنشلة',900,600);
INSERT INTO "delivery_fees" VALUES(41,'سوق أهراس',900,600);
INSERT INTO "delivery_fees" VALUES(42,'تيبازة',850,500);
INSERT INTO "delivery_fees" VALUES(43,'ميلة',850,500);
INSERT INTO "delivery_fees" VALUES(44,'عين الدفلى',850,500);
INSERT INTO "delivery_fees" VALUES(45,'النعامة',1100,800);
INSERT INTO "delivery_fees" VALUES(46,'عين تموشنت',900,600);
INSERT INTO "delivery_fees" VALUES(47,'غرداية',500,400);
INSERT INTO "delivery_fees" VALUES(48,'غليزان',850,500);
INSERT INTO "delivery_fees" VALUES(49,'تيميمون',1400,1100);
INSERT INTO "delivery_fees" VALUES(50,'برج باجي مختار',0,0);
INSERT INTO "delivery_fees" VALUES(51,'أولاد جلال',1000,700);
INSERT INTO "delivery_fees" VALUES(52,'بني عباس',1400,1100);
INSERT INTO "delivery_fees" VALUES(53,'عين صالح',1400,1100);
INSERT INTO "delivery_fees" VALUES(54,'عين قزام',2000,1700);
INSERT INTO "delivery_fees" VALUES(55,'تقرت',1100,800);
INSERT INTO "delivery_fees" VALUES(56,'جانت',2000,1700);
INSERT INTO "delivery_fees" VALUES(57,'المغير',1100,800);
INSERT INTO "delivery_fees" VALUES(58,'المنيعة',1300,1000);
CREATE TABLE feature_flags (
    key TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "feature_flags" VALUES('community',0,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('dark_mode',0,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('discovery',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('gift_finder',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('gift_from_cart',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('gift_from_product',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('gifts',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('ideas_lab',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('on_demand',1,'2026-08-19 23:26:29');
INSERT INTO "feature_flags" VALUES('smart_search',0,'2026-08-19 23:26:29');
CREATE TABLE image_assets (
    id TEXT PRIMARY KEY,
    product_id TEXT,
    storage_provider TEXT NOT NULL CHECK (storage_provider IN ('external', 'r2')),
    object_key TEXT,
    public_url TEXT NOT NULL,
    original_filename TEXT,
    mime_type TEXT,
    byte_size INTEGER CHECK (byte_size IS NULL OR byte_size >= 0),
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    legacy_payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);
INSERT INTO "image_assets" VALUES('legacy-image-bk001','bk001','external',NULL,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',NULL,NULL,NULL,0,'{"product_id":"bk001","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-bk002','bk002','external',NULL,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',NULL,NULL,NULL,0,'{"product_id":"bk002","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-bk003','bk003','external',NULL,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV2LKC-0hByQ4sngJFhFOZXjxGYJhHMiuE2XgUvUVPEA&s=10',NULL,NULL,NULL,0,'{"product_id":"bk003","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-bk004','bk004','external',NULL,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGw5uVSSGRQow8Sxb5MTeIneed3ONpDHBOacdnIkwseQ&s=10',NULL,NULL,NULL,0,'{"product_id":"bk004","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-bk005','bk005','external',NULL,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI_7xZjznLC9j4zEGlBCk8gZliFOxlFwSAVCwGgLeYaw&s=10',NULL,NULL,NULL,0,'{"product_id":"bk005","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-bk007','bk007','external',NULL,'https://i.ibb.co/Y4K1cFxS/1-org-zoom.jpg',NULL,NULL,NULL,0,'{"product_id":"bk007","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-bk008','bk008','external',NULL,'https://i.ibb.co/21YrD35f/c6d5ad31c676a8252efb9a990b4a4585.jpg',NULL,NULL,NULL,0,'{"product_id":"bk008","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK009','BK009','external',NULL,'https://i.ibb.co/kskmG4zc/b3e7df92-a23b-42af-8916-52b68930ceed.jpg',NULL,NULL,NULL,0,'{"product_id":"BK009","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK010','BK010','external',NULL,'https://i.ibb.co/BVcRskzR/40ae280d0de28f8e25497e4f5e4858d2.jpg',NULL,NULL,NULL,0,'{"product_id":"BK010","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK011','BK011','external',NULL,'https://i.ibb.co/sdChybyN/8583fb3e27d675d798d7c8fa8f70a1f0.jpg',NULL,NULL,NULL,0,'{"product_id":"BK011","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK012','BK012','external',NULL,'https://i.ibb.co/7xD9k8LW/8966945c76759578abe3d7d9953a12f4.jpg',NULL,NULL,NULL,0,'{"product_id":"BK012","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK013','BK013','external',NULL,'https://i.ibb.co/NnKBgmXg/545fa2b1-bb11-4d1c-9770-d518187acd7e.jpg',NULL,NULL,NULL,0,'{"product_id":"BK013","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK014','BK014','external',NULL,'https://i.ibb.co/twGmjQpD/001-h-36663346.jpg',NULL,NULL,NULL,0,'{"product_id":"BK014","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK015','BK015','external',NULL,'https://i.ibb.co/qLSGn4Dp/e4db1e2a33e91a15a1c79117ed7cc381.jpg',NULL,NULL,NULL,0,'{"product_id":"BK015","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK016','BK016','external',NULL,'https://i.ibb.co/PsY7dYWy/411323.jpg',NULL,NULL,NULL,0,'{"product_id":"BK016","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK017','BK017','external',NULL,'https://i.ibb.co/cPjN7BK/660ef229719ab20d24a60b8f74ada3ca.jpg',NULL,NULL,NULL,0,'{"product_id":"BK017","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK018','BK018','external',NULL,'https://i.ibb.co/NdvvKhdN/af39613b91506040362940e5b73d75be.jpg',NULL,NULL,NULL,0,'{"product_id":"BK018","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK019','BK019','external',NULL,'https://i.ibb.co/V0Srgjhm/1-org-zoom-2.jpg',NULL,NULL,NULL,0,'{"product_id":"BK019","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK020','BK020','external',NULL,'https://i.ibb.co/jP6nVQWY/34068331-UY630-SR1200-630.jpg',NULL,NULL,NULL,0,'{"product_id":"BK020","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK021','BK021','external',NULL,'https://i.ibb.co/0NGxPCF/f937da8ea10c85b9b45829be297ebded.jpg',NULL,NULL,NULL,0,'{"product_id":"BK021","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK022','BK022','external',NULL,'https://i.ibb.co/pBDT4pY9/8e0f87b7385e03b96ad17a52caa892e2.jpg',NULL,NULL,NULL,0,'{"product_id":"BK022","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "image_assets" VALUES('legacy-image-BK023','BK023','external',NULL,'https://i.ibb.co/kggx5dx8/ab75e9d3-69e1-42a6-b582-0c8010ae55cd.jpg',NULL,NULL,NULL,0,'{"product_id":"BK023","source":"data.json"}','2026-08-19 23:26:29','2026-08-19 23:26:29');
CREATE TABLE migration_batches (
    batch_id TEXT PRIMARY KEY,
    source_sha256 TEXT NOT NULL,
    row_counts_json TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('prepared', 'imported', 'verified', 'rolled_back')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at TEXT
);
INSERT INTO "migration_batches" VALUES('local-d1-dry-run','dbdbe3f160c2a1d48bf0fadc30bac8fdd5fb54c58ca4d9d19b6f118ebf30d685','{"categories":4,"delivery_fees":58,"feature_flags":10,"image_assets":22,"order_gifts":7,"order_items":14,"orders":7,"product_tags":0,"products":22}','prepared','2026-08-19 23:26:29',NULL);
CREATE TABLE order_gifts (
    order_id TEXT PRIMARY KEY,
    source TEXT NOT NULL DEFAULT '',
    sender_name TEXT NOT NULL DEFAULT '',
    recipient_name TEXT NOT NULL DEFAULT '',
    recipient_phone TEXT NOT NULL DEFAULT '',
    recipient_type TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    occasion TEXT NOT NULL DEFAULT '',
    mood TEXT NOT NULL DEFAULT '',
    budget INTEGER CHECK (budget IS NULL OR budget >= 0),
    anonymous INTEGER NOT NULL DEFAULT 0 CHECK (anonymous IN (0, 1)),
    gift_item_ids_json TEXT NOT NULL DEFAULT '[]',
    legacy_payload_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0001','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0002','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0003','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0004','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0005','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0006','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
INSERT INTO "order_gifts" VALUES('legacy-order-ORD-0007','cart','اختبار','قارئ التجربة','0550000000','friend','','birthday','warm',0,0,'["bk001"]','{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"}');
CREATE TABLE order_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id TEXT NOT NULL,
    line_number INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    item_role TEXT NOT NULL CHECK (item_role IN ('personal', 'gift')),
    title_snapshot TEXT NOT NULL DEFAULT '',
    image_snapshot TEXT NOT NULL DEFAULT '',
    price_snapshot INTEGER NOT NULL DEFAULT 0 CHECK (price_snapshot >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    purchase_purpose TEXT NOT NULL DEFAULT '',
    availability_type TEXT NOT NULL DEFAULT '',
    lead_time_min_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_min_days BETWEEN 0 AND 1),
    lead_time_max_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_max_days BETWEEN 0 AND 1),
    legacy_payload_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id),
    UNIQUE (order_id, line_number)
);
INSERT INTO "order_items" VALUES(1,'legacy-order-ORD-0001',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(2,'legacy-order-ORD-0001',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
INSERT INTO "order_items" VALUES(3,'legacy-order-ORD-0002',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(4,'legacy-order-ORD-0002',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
INSERT INTO "order_items" VALUES(5,'legacy-order-ORD-0003',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(6,'legacy-order-ORD-0003',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
INSERT INTO "order_items" VALUES(7,'legacy-order-ORD-0004',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(8,'legacy-order-ORD-0004',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
INSERT INTO "order_items" VALUES(9,'legacy-order-ORD-0005',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(10,'legacy-order-ORD-0005',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
INSERT INTO "order_items" VALUES(11,'legacy-order-ORD-0006',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(12,'legacy-order-ORD-0006',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
INSERT INTO "order_items" VALUES(13,'legacy-order-ORD-0007',1,'bk002','personal','دقات الشامو','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,1,'personal','in_stock',0,0,'{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}');
INSERT INTO "order_items" VALUES(14,'legacy-order-ORD-0007',2,'bk001','gift','قواعد جارتين','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,1,'gift','in_stock',0,0,'{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}');
CREATE TABLE orders (
    id TEXT PRIMARY KEY,
    legacy_order_id TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('new', 'confirmed', 'awaiting_supply', 'processing', 'ready_to_ship', 'shipped', 'delivered', 'cancelled', 'returned')),
    customer_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    wilaya TEXT NOT NULL DEFAULT '',
    delivery_type TEXT NOT NULL DEFAULT '',
    delivery_fee INTEGER NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    order_type TEXT NOT NULL DEFAULT '',
    shipping_policy TEXT NOT NULL DEFAULT '',
    fulfillment_note TEXT NOT NULL DEFAULT '',
    subtotal INTEGER NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    total INTEGER NOT NULL DEFAULT 0 CHECK (total >= 0),
    source_timestamp TEXT NOT NULL DEFAULT '',
    idempotency_key TEXT UNIQUE,
    legacy_status TEXT,
    legacy_payload_json TEXT NOT NULL DEFAULT '{}',
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "orders" VALUES('legacy-order-ORD-0001','ORD-0001','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-18T23:24:18.342620',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0001","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-18T23:24:18.342620","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "orders" VALUES('legacy-order-ORD-0002','ORD-0002','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-18T23:45:02.907886',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0002","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-18T23:45:02.907886","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "orders" VALUES('legacy-order-ORD-0003','ORD-0003','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-18T23:46:09.311644',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0003","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-18T23:46:09.311644","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "orders" VALUES('legacy-order-ORD-0004','ORD-0004','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-18T23:52:07.371215',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0004","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-18T23:52:07.371215","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "orders" VALUES('legacy-order-ORD-0005','ORD-0005','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-18T23:52:58.566485',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0005","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-18T23:52:58.566485","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "orders" VALUES('legacy-order-ORD-0006','ORD-0006','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-19T00:16:28.547262',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0006","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-19T00:16:28.547262","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "orders" VALUES('legacy-order-ORD-0007','ORD-0007','new','اختبار','0550000000','عنوان تجريبي','الجزائر','Domicile',850,'mixed','ship_together','جميع الكتب متوفرة من المخزون.',2400,3250,'2026-08-19T06:41:36.319468',NULL,NULL,'{"address":"عنوان تجريبي","customer_name":"اختبار","delivery_fee":850,"delivery_type":"Domicile","fulfillment_note":"جميع الكتب متوفرة من المخزون.","gift":{"anonymous":false,"budget":0,"gift_item_ids":["bk001"],"message":"","mood":"warm","occasion":"birthday","recipient_name":"قارئ التجربة","recipient_phone":"0550000000","recipient_type":"friend","sender_name":"اختبار","source":"cart"},"gift_items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"}],"items":[{"availability_type":"in_stock","id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"gift","qty":1,"title":"قواعد جارتين"},{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"order_id":"ORD-0007","order_type":"mixed","personal_items":[{"availability_type":"in_stock","id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"purchase_purpose":"personal","qty":1,"title":"دقات الشامو"}],"phone":"0550000000","shipping_policy":"ship_together","status":"new","subtotal":2400,"timestamp":"2026-08-19T06:41:36.319468","total":3250,"wilaya":"الجزائر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
CREATE TABLE product_tags (
    product_id TEXT NOT NULL,
    tag_type TEXT NOT NULL CHECK (tag_type IN ('discovery', 'gift')),
    tag TEXT NOT NULL,
    PRIMARY KEY (product_id, tag_type, tag),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
CREATE TABLE products (
    id TEXT PRIMARY KEY,
    legacy_id TEXT NOT NULL UNIQUE,
    category_slug TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    image_url TEXT NOT NULL DEFAULT '',
    price INTEGER NOT NULL CHECK (price >= 0),
    stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    availability_type TEXT NOT NULL CHECK (availability_type IN ('in_stock', 'on_demand')),
    lead_time_min_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_min_days BETWEEN 0 AND 1),
    lead_time_max_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_max_days BETWEEN 0 AND 1),
    lead_time_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_time_days BETWEEN 0 AND 1),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0, 1)),
    giftable INTEGER NOT NULL DEFAULT 0 CHECK (giftable IN (0, 1)),
    discoverable INTEGER NOT NULL DEFAULT 1 CHECK (discoverable IN (0, 1)),
    archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    legacy_payload_json TEXT NOT NULL DEFAULT '{}',
    schema_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_slug) REFERENCES categories(slug),
    CHECK (lead_time_min_days <= lead_time_max_days),
    CHECK (availability_type = 'in_stock' OR lead_time_max_days <= 1)
);
INSERT INTO "products" VALUES('bk001','bk001','روايات','قواعد جارتين','تدور أحداث الرواية في عالم خيالي يُعرف باسم جارتين، وهو مجتمع تحكمه قوانين صارمة وغامضة تتحكم في تفاصيل حياة السكان، مثل العمر، والانتماء الطبقي، والعلاقات بين الناس. يبدأ كل شيء عندما يصل طبيب شاب إلى هذا العالم، ليكتشف تدريجيًا أن القواعد التي يراها الجميع مسلّمات تخفي وراءها أسرارًا كبيرة، وأن تغيير هذا الواقع قد يكون مكلفًا للغاية.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تدور أحداث الرواية في عالم خيالي يُعرف باسم جارتين، وهو مجتمع تحكمه قوانين صارمة وغامضة تتحكم في تفاصيل حياة السكان، مثل العمر، والانتماء الطبقي، والعلاقات بين الناس. يبدأ كل شيء عندما يصل طبيب شاب إلى هذا العالم، ليكتشف تدريجيًا أن القواعد التي يراها الجميع مسلّمات تخفي وراءها أسرارًا كبيرة، وأن تغيير هذا الواقع قد يكون مكلفًا للغاية.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk001","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXtuCUwbjOMSvrUSoJ46PnB1f2Lg5uR0N1bxZtQ1_MnQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"قواعد جارتين"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('bk002','bk002','روايات','دقات الشامو','تبدأ الرواية بعد انهيار الأمل في تحقيق التغيير، حيث تعم الفوضى وادي النسالى، ويجد الأبطال أنفسهم في مواجهة تحديات جديدة، بينما تنكشف أسرار عن الماضي وتتشابك مصائر الشخصيات. ومع تصاعد الصراع، تصبح المعركة ليست فقط من أجل البقاء، بل من أجل تغيير النظام الذي يحكم عالم جارتين.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تبدأ الرواية بعد انهيار الأمل في تحقيق التغيير، حيث تعم الفوضى وادي النسالى، ويجد الأبطال أنفسهم في مواجهة تحديات جديدة، بينما تنكشف أسرار عن الماضي وتتشابك مصائر الشخصيات. ومع تصاعد الصراع، تصبح المعركة ليست فقط من أجل البقاء، بل من أجل تغيير النظام الذي يحكم عالم جارتين.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk002","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi8pkJEcs_yob-O8p2lGzVJi1DFDSEGqeOe-VZOQIJRw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"دقات الشامو"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('bk003','bk003','روايات','أمواج أكما','تستكمل الرواية الأحداث التي انتهى عندها الجزء الثاني (دقات الشامو)، حيث يشتد الصراع بين طبقات المجتمع في عالم "جارتين". تدور القصة حول محاولات كسر القوانين الظالمة التي كرّست التمييز بين الناس، وتتصاعد المواجهات حتى تصل إلى خاتمة تكشف العديد من الأسرار التي بُني عليها هذا العالم الخيالي','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV2LKC-0hByQ4sngJFhFOZXjxGYJhHMiuE2XgUvUVPEA&s=10',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تستكمل الرواية الأحداث التي انتهى عندها الجزء الثاني (دقات الشامو)، حيث يشتد الصراع بين طبقات المجتمع في عالم \"جارتين\". تدور القصة حول محاولات كسر القوانين الظالمة التي كرّست التمييز بين الناس، وتتصاعد المواجهات حتى تصل إلى خاتمة تكشف العديد من الأسرار التي بُني عليها هذا العالم الخيالي","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk003","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV2LKC-0hByQ4sngJFhFOZXjxGYJhHMiuE2XgUvUVPEA&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"أمواج أكما"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('bk004','bk004','روايات','متلازمة فريجولي','نادر اخصائي نفسي تجبره ظروف الحياة ليتولى في وظيفته الاولى حاله مراهق مصاب باندر واغرب الاضطرابات النفسية متلازمة فريجولي منتحلا هوية طبيب نفسي اخر ليكتشف في يوم عمله الاول ان لا احد يرغب في شفاء الفتى لا المشفى ولا عائلته ولا حتى نادر نفسه
 متلازمة فريجولي هو اضطراب نادر يصيب الشخص ويجعله يتخيل اوهام مثل اعتقاد ان الاشخاص الذين حوله جميعهم شخص واحد — يتنكر في هيئات مختلفة ليظهر كأشخاص اخرين سواء من الجنس نفسه او الجنس الاخر...','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGw5uVSSGRQow8Sxb5MTeIneed3ONpDHBOacdnIkwseQ&s=10',1500,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"نادر اخصائي نفسي تجبره ظروف الحياة ليتولى في وظيفته الاولى حاله مراهق مصاب باندر واغرب الاضطرابات النفسية متلازمة فريجولي منتحلا هوية طبيب نفسي اخر ليكتشف في يوم عمله الاول ان لا احد يرغب في شفاء الفتى لا المشفى ولا عائلته ولا حتى نادر نفسه\n متلازمة فريجولي هو اضطراب نادر يصيب الشخص ويجعله يتخيل اوهام مثل اعتقاد ان الاشخاص الذين حوله جميعهم شخص واحد — يتنكر في هيئات مختلفة ليظهر كأشخاص اخرين سواء من الجنس نفسه او الجنس الاخر...","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk004","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGw5uVSSGRQow8Sxb5MTeIneed3ONpDHBOacdnIkwseQ&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1500,"stock_quantity":10,"title":"متلازمة فريجولي"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('bk005','bk005','روايات','شمس منتصف الليل','رواية شمس منتصف الليل 📖
تدور الأحداث في مدينة (فانكوفر ) بكندا ، تأخذنا في رحلة متنقلة بين حياة ( تالين ) فتاة جامعية مُحبة تعيش مع عائلتها ،تجمع بين الثقافة اليونانية والتي ورثتها من والدتها والثقافة المصرية من والدها وكيف ستقتل بالحَب ،و المحقق (بيتر)صديق الطفولة لـ (تالين ) يكبرها بثلاثة أعوام والذي يطارد قاتل وحشي متسلسل الجرام يُعرف (ازار )، وستتعرف أيضاً عن (وهج )الفتاة الرقيقة التي تعيش مع أمها قاسية القلب وزوجها المتحرش بعد أن تخلي عنها والدها منذ يومها الأول بالحياة ، وأخيراً ستتعرف عن (جوليان )ذلك الفتي الذي أنتحرت حبيبته بعد معاناتها من نقص المال والإبتزاز والخيانة ممن حولها .فكيف وقعت تالين بالحب وماذا يخبئ لها القدر ؟ هل سيستطيع (بيتر)أن يقبض علي القاتل وكيف سيكشف هويته الحقيقة؟ هل ستجد (وهج )والدها او ماذا سيحدث لها بعد ماحدث من والدتها وزوجها ؟ كيف سيعيش (جوليان )حياته بعد إنتحار حب حياته ؟ ما المفاجآت التي ستحدث وما هي علاقة الشخصيات ببعضهم البعض؟
•رواية واقعية تجمع في طياتها بين الرومانسية والجريمة والغموض ، أحببت الحبكة جداً وطريقة السرد غير مملة ، أستطيع الكاتب أن يعطي كل شخصية حقها بالظهور والأحداث ووصف حالتهم بكل أداع وكيف بني علاقات بين الشخصيات ، فقط لم تعجبني معظم الرسائل الغرامية الذي وجدتها مبالغ فيها وتوقعت بعض الأحداث ،ولكن النهاية كانت صادمة ورائعة وموفقة جداً .','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI_7xZjznLC9j4zEGlBCk8gZliFOxlFwSAVCwGgLeYaw&s=10',1500,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"رواية شمس منتصف الليل 📖\nتدور الأحداث في مدينة (فانكوفر ) بكندا ، تأخذنا في رحلة متنقلة بين حياة ( تالين ) فتاة جامعية مُحبة تعيش مع عائلتها ،تجمع بين الثقافة اليونانية والتي ورثتها من والدتها والثقافة المصرية من والدها وكيف ستقتل بالحَب ،و المحقق (بيتر)صديق الطفولة لـ (تالين ) يكبرها بثلاثة أعوام والذي يطارد قاتل وحشي متسلسل الجرام يُعرف (ازار )، وستتعرف أيضاً عن (وهج )الفتاة الرقيقة التي تعيش مع أمها قاسية القلب وزوجها المتحرش بعد أن تخلي عنها والدها منذ يومها الأول بالحياة ، وأخيراً ستتعرف عن (جوليان )ذلك الفتي الذي أنتحرت حبيبته بعد معاناتها من نقص المال والإبتزاز والخيانة ممن حولها .فكيف وقعت تالين بالحب وماذا يخبئ لها القدر ؟ هل سيستطيع (بيتر)أن يقبض علي القاتل وكيف سيكشف هويته الحقيقة؟ هل ستجد (وهج )والدها او ماذا سيحدث لها بعد ماحدث من والدتها وزوجها ؟ كيف سيعيش (جوليان )حياته بعد إنتحار حب حياته ؟ ما المفاجآت التي ستحدث وما هي علاقة الشخصيات ببعضهم البعض؟\n•رواية واقعية تجمع في طياتها بين الرومانسية والجريمة والغموض ، أحببت الحبكة جداً وطريقة السرد غير مملة ، أستطيع الكاتب أن يعطي كل شخصية حقها بالظهور والأحداث ووصف حالتهم بكل أداع وكيف بني علاقات بين الشخصيات ، فقط لم تعجبني معظم الرسائل الغرامية الذي وجدتها مبالغ فيها وتوقعت بعض الأحداث ،ولكن النهاية كانت صادمة ورائعة وموفقة جداً .","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk005","img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI_7xZjznLC9j4zEGlBCk8gZliFOxlFwSAVCwGgLeYaw&s=10","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1500,"stock_quantity":10,"title":"شمس منتصف الليل"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('bk007','bk007','روايات','رواية 005','حين يُكلَّف القاتل المأجور الأشهر، المعروف بالرمز 005، باغتيال فتاة تعيش حياة هادئة لا تعلم شيئًا عن العالم المظلم الذي يحيط بها، تنقلب حياتها في لحظة واحدة. وبين مطاردة لا تعرف سببها، وأسرار تُكشف تباعًا، تجد نفسها وجهاً لوجه مع أخطر رجل في عالم الجريمة.
في عالم تحكمه العصابات والولاءات القاتلة، تتحول مهمة اغتيال إلى رحلة مليئة بالمفاجآت، حيث يمتزج التشويق بالرومانسية المظلمة، ويصبح الخط الفاصل بين العدو والمنقذ أكثر غموضًا مع كل صفحة. رواية 005 للكاتبة شهد قربان تقدم تجربة آسرة لمحبي الإثارة والغموض، بقصة متصاعدة وأحداث لا تتوقف عن إدهاش القارئ حتى النهاية.','https://i.ibb.co/Y4K1cFxS/1-org-zoom.jpg',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"حين يُكلَّف القاتل المأجور الأشهر، المعروف بالرمز 005، باغتيال فتاة تعيش حياة هادئة لا تعلم شيئًا عن العالم المظلم الذي يحيط بها، تنقلب حياتها في لحظة واحدة. وبين مطاردة لا تعرف سببها، وأسرار تُكشف تباعًا، تجد نفسها وجهاً لوجه مع أخطر رجل في عالم الجريمة.\nفي عالم تحكمه العصابات والولاءات القاتلة، تتحول مهمة اغتيال إلى رحلة مليئة بالمفاجآت، حيث يمتزج التشويق بالرومانسية المظلمة، ويصبح الخط الفاصل بين العدو والمنقذ أكثر غموضًا مع كل صفحة. رواية 005 للكاتبة شهد قربان تقدم تجربة آسرة لمحبي الإثارة والغموض، بقصة متصاعدة وأحداث لا تتوقف عن إدهاش القارئ حتى النهاية.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk007","img":"https://i.ibb.co/Y4K1cFxS/1-org-zoom.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"رواية 005"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('bk008','bk008','روايات','حقل التفاح','تأخذ القصة منحى أكثر إنسائية وعمقا نفسيا، حيث يعود " نادر" المعالج النفسي، إلى قريته بعد غياب طويل، برفقة مراهق يعاني من متلازمة فريجولي ومن هنا تبدأ رحلة مليئة بكشف اسرار الماضي، ومواجهة صراعات داخلية ترتبط بالقرية، العائلة، وحتى معنى الحياة نفسها
 السلسلة تمزج ببراعة بين الغموض، الدراما، والفلسفة، بأسلوب مشوق يجعلك غير قادر على ترك الكتاب.','https://i.ibb.co/21YrD35f/c6d5ad31c676a8252efb9a990b4a4585.jpg',1500,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تأخذ القصة منحى أكثر إنسائية وعمقا نفسيا، حيث يعود \" نادر\" المعالج النفسي، إلى قريته بعد غياب طويل، برفقة مراهق يعاني من متلازمة فريجولي ومن هنا تبدأ رحلة مليئة بكشف اسرار الماضي، ومواجهة صراعات داخلية ترتبط بالقرية، العائلة، وحتى معنى الحياة نفسها\n السلسلة تمزج ببراعة بين الغموض، الدراما، والفلسفة، بأسلوب مشوق يجعلك غير قادر على ترك الكتاب.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"bk008","img":"https://i.ibb.co/21YrD35f/c6d5ad31c676a8252efb9a990b4a4585.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1500,"stock_quantity":10,"title":"حقل التفاح"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK009','BK009','روايات','البارون','جزء الثالث من رواية 005 تدور أحداث الرواية حول روبي التي تلتقي مجددًا بـمارسيل، معتقدةً أن الحب قد يمنحهما فرصة لبداية جديدة. لكن سرعان ما تكتشف أن مارسيل ما يزال الرجل الغامض والعنيد نفسه، وأن العلاقة بينهما أصبحت أكثر تعقيدًا من السابق. وفي الوقت ذاته، تجد نفسها محاصرة بخطر يترصدها من الظل، لتتشابك الأحداث بين الصراع العاطفي والغموض والجريمة.','https://i.ibb.co/kskmG4zc/b3e7df92-a23b-42af-8916-52b68930ceed.jpg',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"جزء الثالث من رواية 005 تدور أحداث الرواية حول روبي التي تلتقي مجددًا بـمارسيل، معتقدةً أن الحب قد يمنحهما فرصة لبداية جديدة. لكن سرعان ما تكتشف أن مارسيل ما يزال الرجل الغامض والعنيد نفسه، وأن العلاقة بينهما أصبحت أكثر تعقيدًا من السابق. وفي الوقت ذاته، تجد نفسها محاصرة بخطر يترصدها من الظل، لتتشابك الأحداث بين الصراع العاطفي والغموض والجريمة.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK009","img":"https://i.ibb.co/kskmG4zc/b3e7df92-a23b-42af-8916-52b68930ceed.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"البارون"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK010','BK010','روايات','ستوكهولم','تبدأ الأحداث بعد نهاية رواية 005، حيث تجد روبي سميث نفسها عالقة بين القاتل الغامض المعروف بـ«005» وإحدى أخطر العائلات الإجرامية في العالم. وبينما تحاول النجاة وبناء حياة جديدة، تنجرف إلى سلسلة من الأحداث المليئة بالغموض والخطر، وتتطور علاقتها بشخصية غامضة بطريقة تعكس مفهوم متلازمة ستوكهولم؛ حيث تختلط مشاعر الخوف بالتعلق، وتصبح الحدود بين العدو والحبيب غير واضحة.','https://i.ibb.co/BVcRskzR/40ae280d0de28f8e25497e4f5e4858d2.jpg',1000,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تبدأ الأحداث بعد نهاية رواية 005، حيث تجد روبي سميث نفسها عالقة بين القاتل الغامض المعروف بـ«005» وإحدى أخطر العائلات الإجرامية في العالم. وبينما تحاول النجاة وبناء حياة جديدة، تنجرف إلى سلسلة من الأحداث المليئة بالغموض والخطر، وتتطور علاقتها بشخصية غامضة بطريقة تعكس مفهوم متلازمة ستوكهولم؛ حيث تختلط مشاعر الخوف بالتعلق، وتصبح الحدود بين العدو والحبيب غير واضحة.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK010","img":"https://i.ibb.co/BVcRskzR/40ae280d0de28f8e25497e4f5e4858d2.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1000,"stock_quantity":10,"title":"ستوكهولم"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK011','BK011','روايات','لأنها كيارا','تبدأ الأحداث مع كيارا، فتاة تستيقظ بعد أن تعرضت للاختطاف والإعدام حرقًا، لكنها تجد نفسها بصورة غامضة في منزل زميلها أليكس، الذي تكتشف لاحقًا أنه ليس إنسانًا عاديًا، بل مصاص دماء. ومن هنا تنطلق رحلة مليئة بالأسرار لاكتشاف حقيقتها، والإجابة عن أسئلة مصيرية: من هي كيارا؟ ولماذا استُهدفت؟ وكيف نجت من الموت؟','https://i.ibb.co/sdChybyN/8583fb3e27d675d798d7c8fa8f70a1f0.jpg',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تبدأ الأحداث مع كيارا، فتاة تستيقظ بعد أن تعرضت للاختطاف والإعدام حرقًا، لكنها تجد نفسها بصورة غامضة في منزل زميلها أليكس، الذي تكتشف لاحقًا أنه ليس إنسانًا عاديًا، بل مصاص دماء. ومن هنا تنطلق رحلة مليئة بالأسرار لاكتشاف حقيقتها، والإجابة عن أسئلة مصيرية: من هي كيارا؟ ولماذا استُهدفت؟ وكيف نجت من الموت؟","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK011","img":"https://i.ibb.co/sdChybyN/8583fb3e27d675d798d7c8fa8f70a1f0.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"لأنها كيارا"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK012','BK012','روايات','مملكات الكوابيس والضباب','تدور الرواية حول الأميرة لورا، التي تعيش في مملكة يغلفها الضباب، لكنها تعاني من كوابيس مرعبة لا تبقى مجرد أحلام، بل تتحول إلى أحداث حقيقية تهدد مملكتها. وبينما تحاول فهم سر هذه اللعنة، تنطلق في رحلة مليئة بالمخاطر، تواجه خلالها مخلوقات غامضة وأسرارًا قديمة، وتكتشف حقائق قد تغيّر مصير المملكة والعائلة المالكة إلى الأبد.','https://i.ibb.co/7xD9k8LW/8966945c76759578abe3d7d9953a12f4.jpg',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تدور الرواية حول الأميرة لورا، التي تعيش في مملكة يغلفها الضباب، لكنها تعاني من كوابيس مرعبة لا تبقى مجرد أحلام، بل تتحول إلى أحداث حقيقية تهدد مملكتها. وبينما تحاول فهم سر هذه اللعنة، تنطلق في رحلة مليئة بالمخاطر، تواجه خلالها مخلوقات غامضة وأسرارًا قديمة، وتكتشف حقائق قد تغيّر مصير المملكة والعائلة المالكة إلى الأبد.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK012","img":"https://i.ibb.co/7xD9k8LW/8966945c76759578abe3d7d9953a12f4.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"مملكات الكوابيس والضباب"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK013','BK013','روايات','العرش الأسود','في عالمٍ تمزقه الحروب بين المخلوقات الأسطورية، تجد كيارا نفسها أمام أخطر اختبار في رحلتها. تتشابك الأسرار القديمة مع الصراعات الحالية، وتصبح كل خطوة تتخذها قادرة على تغيير مصير الممالك بأكملها. وبين سجين غامض يخفي أسرارًا قديمة واحتفالٍ طال انتظاره ينقلب إلى كارثة، تُجبر كيارا على مواجهة حقيقتها واتخاذ قرارات مصيرية لا عودة عنها.','https://i.ibb.co/NnKBgmXg/545fa2b1-bb11-4d1c-9770-d518187acd7e.jpg',1200,0,'on_demand',1,1,1,1,0,1,1,0,'{"active":true,"availability_type":"on_demand","category":"روايات","desc":"في عالمٍ تمزقه الحروب بين المخلوقات الأسطورية، تجد كيارا نفسها أمام أخطر اختبار في رحلتها. تتشابك الأسرار القديمة مع الصراعات الحالية، وتصبح كل خطوة تتخذها قادرة على تغيير مصير الممالك بأكملها. وبين سجين غامض يخفي أسرارًا قديمة واحتفالٍ طال انتظاره ينقلب إلى كارثة، تُجبر كيارا على مواجهة حقيقتها واتخاذ قرارات مصيرية لا عودة عنها.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK013","img":"https://i.ibb.co/NnKBgmXg/545fa2b1-bb11-4d1c-9770-d518187acd7e.jpg","lead_time_days":1,"lead_time_max_days":1,"lead_time_min_days":1,"price":1200,"stock_quantity":0,"title":"العرش الأسود"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK014','BK014','تنمية-بشرية','العادات الذرية','هو كتاب من تأليف جيمس كلير، يركز على كيفية بناء العادات الجيدة والتخلص من العادات السيئة من خلال تغييرات صغيرة ومتراكمة، بدلًا من الاعتماد على الحافز أو الإرادة وحدهما.
يرى المؤلف أن التحسينات الصغيرة اليومية، حتى لو كانت بنسبة 1% فقط، يمكن أن تؤدي إلى نتائج كبيرة مع مرور الوقت. ويشرح أن النجاح ليس نتيجة قرارات ضخمة، بل هو حصيلة العادات التي نكررها باستمرار.','https://i.ibb.co/twGmjQpD/001-h-36663346.jpg',1300,2,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"تنمية بشرية","desc":"هو كتاب من تأليف جيمس كلير، يركز على كيفية بناء العادات الجيدة والتخلص من العادات السيئة من خلال تغييرات صغيرة ومتراكمة، بدلًا من الاعتماد على الحافز أو الإرادة وحدهما.\nيرى المؤلف أن التحسينات الصغيرة اليومية، حتى لو كانت بنسبة 1% فقط، يمكن أن تؤدي إلى نتائج كبيرة مع مرور الوقت. ويشرح أن النجاح ليس نتيجة قرارات ضخمة، بل هو حصيلة العادات التي نكررها باستمرار.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK014","img":"https://i.ibb.co/twGmjQpD/001-h-36663346.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1300,"stock_quantity":2,"title":"العادات الذرية"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK015','BK015','تنمية-بشرية','فاتتني صلاة','يركز الكتاب على الإجابة عن سؤال بسيط لكنه عميق: لماذا تثقل الصلاة على بعض الناس، بينما يجد فيها آخرون راحة وسكينة؟ ومن خلال أسلوب سهل وقريب من القارئ، يشرح المؤلف مكانة الصلاة في حياة المسلم، ويعرض أسباب التقصير فيها، ويقترح وسائل عملية تساعد على المحافظة عليها.','https://i.ibb.co/qLSGn4Dp/e4db1e2a33e91a15a1c79117ed7cc381.jpg',850,2,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"تنمية بشرية","desc":"يركز الكتاب على الإجابة عن سؤال بسيط لكنه عميق: لماذا تثقل الصلاة على بعض الناس، بينما يجد فيها آخرون راحة وسكينة؟ ومن خلال أسلوب سهل وقريب من القارئ، يشرح المؤلف مكانة الصلاة في حياة المسلم، ويعرض أسباب التقصير فيها، ويقترح وسائل عملية تساعد على المحافظة عليها.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK015","img":"https://i.ibb.co/qLSGn4Dp/e4db1e2a33e91a15a1c79117ed7cc381.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":850,"stock_quantity":2,"title":"فاتتني صلاة"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK016','BK016','روايات','سجناء 1500 عام','تخيل مجتمعًا يعيش في باطن الأرض منذ ما يقارب 1500 عام، وقد نسي تمامًا شكل العالم الخارجي. أصبح سكان هذا العالم يعتبرون قصص الأجداد عن السماء والشمس والطبيعة مجرد خرافات لا أساس لها.
تتغير حياة الشاب يزن عندما يعثر على كبسولة زمنية تعود إلى قرون مضت، تحتوي على أشياء ورسائل لا تشبه عالمهم بأي شكل. يثير هذا الاكتشاف فضوله، فيبدأ بالتشكيك في كل ما آمن به، ويقرر مع أصدقائه خوض رحلة خطيرة لاكتشاف الحقيقة: هل يوجد حقًا عالم فوق سطح الأرض؟','https://i.ibb.co/PsY7dYWy/411323.jpg',1300,1,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تخيل مجتمعًا يعيش في باطن الأرض منذ ما يقارب 1500 عام، وقد نسي تمامًا شكل العالم الخارجي. أصبح سكان هذا العالم يعتبرون قصص الأجداد عن السماء والشمس والطبيعة مجرد خرافات لا أساس لها.\nتتغير حياة الشاب يزن عندما يعثر على كبسولة زمنية تعود إلى قرون مضت، تحتوي على أشياء ورسائل لا تشبه عالمهم بأي شكل. يثير هذا الاكتشاف فضوله، فيبدأ بالتشكيك في كل ما آمن به، ويقرر مع أصدقائه خوض رحلة خطيرة لاكتشاف الحقيقة: هل يوجد حقًا عالم فوق سطح الأرض؟","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK016","img":"https://i.ibb.co/PsY7dYWy/411323.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1300,"stock_quantity":1,"title":"سجناء 1500 عام"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK017','BK017','روايات','جمرة','تتمحور القصة حول جمرة، وهي فتاة عاشت طفولة قاسية بسبب نظرة المجتمع إليها، إذ كانت والدتها محاسن معروفة بممارسات غامضة تتعلق بطرد الجن والشعوذة. تكبر جمرة وهي محاطة بالخوف والنبذ، وتتعرض لأحداث مرعبة تكشف تدريجيًا أسرارًا عن عالم خفي يمتزج فيه الواقع بالخرافة والأساطير الشعبية.','https://i.ibb.co/cPjN7BK/660ef229719ab20d24a60b8f74ada3ca.jpg',1200,2,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تتمحور القصة حول جمرة، وهي فتاة عاشت طفولة قاسية بسبب نظرة المجتمع إليها، إذ كانت والدتها محاسن معروفة بممارسات غامضة تتعلق بطرد الجن والشعوذة. تكبر جمرة وهي محاطة بالخوف والنبذ، وتتعرض لأحداث مرعبة تكشف تدريجيًا أسرارًا عن عالم خفي يمتزج فيه الواقع بالخرافة والأساطير الشعبية.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK017","img":"https://i.ibb.co/cPjN7BK/660ef229719ab20d24a60b8f74ada3ca.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":2,"title":"جمرة"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK018','BK018','روايات','أنني أتعفن رعبا','تدور  القصة حول فتاة تُدعى ماريا تعاني منذ طفولتها من كوابيس مرعبة ومتكررة تفوق قدرتها على الاحتمال. وبعد أن تفشل محاولات علاجها، تنصحها والدتها بالتنفيس عن مخاوفها عبر الرسم، فتبدأ بتحويل كوابيسها إلى لوحات فنية.
مع مرور الوقت، تصبح ماريا رسامة مشهورة، لكن الأمور تنقلب عندما تبدأ الأحداث التي رسمتها في لوحاتها بالتحقق على أرض الواقع، لتجد نفسها وسط سلسلة من الوقائع المرعبة التي تجعلها عاجزة عن التمييز بين الحقيقة والخيال، وتدخل في صراع مع أسرار غامضة وماضٍ مظلم.','https://i.ibb.co/NdvvKhdN/af39613b91506040362940e5b73d75be.jpg',1400,1,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تدور  القصة حول فتاة تُدعى ماريا تعاني منذ طفولتها من كوابيس مرعبة ومتكررة تفوق قدرتها على الاحتمال. وبعد أن تفشل محاولات علاجها، تنصحها والدتها بالتنفيس عن مخاوفها عبر الرسم، فتبدأ بتحويل كوابيسها إلى لوحات فنية.\nمع مرور الوقت، تصبح ماريا رسامة مشهورة، لكن الأمور تنقلب عندما تبدأ الأحداث التي رسمتها في لوحاتها بالتحقق على أرض الواقع، لتجد نفسها وسط سلسلة من الوقائع المرعبة التي تجعلها عاجزة عن التمييز بين الحقيقة والخيال، وتدخل في صراع مع أسرار غامضة وماضٍ مظلم.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK018","img":"https://i.ibb.co/NdvvKhdN/af39613b91506040362940e5b73d75be.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1400,"stock_quantity":1,"title":"أنني أتعفن رعبا"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK019','BK019','روايات','آخر موعد للقتل','الرواية للكاتب الألماني أندرياس جروبر هي رواية بوليسية وتشويق نفسي تدور حول مطاردة قاتل متسلسل شديد الذكاء يضع المحققين في سباق مع الزمن.
تبدأ الأحداث عندما يختطف القاتل ضحاياه ويرسل رسالة مرعبة مفادها: إذا تمكنت الشرطة من معرفة سبب اختطاف الضحية خلال 48 ساعة فستنجو، وإلا فسيقتلها. ومع تكرار الجرائم بطرق وحشية وغير مألوفة، تتولى المحققة سابين نيميز التحقيق، ثم تستعين بالمحقق الهولندي مارتن شنايدر، ليكتشفا أن الجرائم مستوحاة من كتاب أطفال قديم يخفي مفتاحًا لفهم نمط القاتل ودوافعه.','https://i.ibb.co/V0Srgjhm/1-org-zoom-2.jpg',1300,1,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"الرواية للكاتب الألماني أندرياس جروبر هي رواية بوليسية وتشويق نفسي تدور حول مطاردة قاتل متسلسل شديد الذكاء يضع المحققين في سباق مع الزمن.\nتبدأ الأحداث عندما يختطف القاتل ضحاياه ويرسل رسالة مرعبة مفادها: إذا تمكنت الشرطة من معرفة سبب اختطاف الضحية خلال 48 ساعة فستنجو، وإلا فسيقتلها. ومع تكرار الجرائم بطرق وحشية وغير مألوفة، تتولى المحققة سابين نيميز التحقيق، ثم تستعين بالمحقق الهولندي مارتن شنايدر، ليكتشفا أن الجرائم مستوحاة من كتاب أطفال قديم يخفي مفتاحًا لفهم نمط القاتل ودوافعه.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK019","img":"https://i.ibb.co/V0Srgjhm/1-org-zoom-2.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1300,"stock_quantity":1,"title":"آخر موعد للقتل"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK020','BK020','روايات','إيكادولي','تدور الأحداث حول الشاب أنس الذي يجد نفسه ينتقل إلى عالم خيالي يُعرف بـمملكة البلاغة، حيث تخوض مجموعة من المحاربين معركة لحماية الكتب والكلمات والقيم من قوى الشر. وخلال رحلته يلتقي بشخصيات عديدة، أبرزها مرام، ويخوضان معًا مغامرات مليئة بالتشويق والصراع بين الخير والشر، مع إبراز مفهوم الحب النقي والوفاء والتضحية.','https://i.ibb.co/jP6nVQWY/34068331-UY630-SR1200-630.jpg',1200,1,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تدور الأحداث حول الشاب أنس الذي يجد نفسه ينتقل إلى عالم خيالي يُعرف بـمملكة البلاغة، حيث تخوض مجموعة من المحاربين معركة لحماية الكتب والكلمات والقيم من قوى الشر. وخلال رحلته يلتقي بشخصيات عديدة، أبرزها مرام، ويخوضان معًا مغامرات مليئة بالتشويق والصراع بين الخير والشر، مع إبراز مفهوم الحب النقي والوفاء والتضحية.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK020","img":"https://i.ibb.co/jP6nVQWY/34068331-UY630-SR1200-630.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":1,"title":"إيكادولي"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK021','BK021','روايات','أكتب حتى لا أصاب بالجنون','رواية رعب نفسي وغموض للكاتبة مريم الحيسي، وتمثل الجزء الثاني من سلسلة «أكتب حتى لا يأكلني الشيطان»، لذا يُفضَّل قراءة الجزء الأول قبلها لفهم الشخصيات والخلفية بشكل كامل.
تتابع الرواية رحلة ماريان بعد الأحداث السابقة، حيث تجد نفسها على حافة الانهيار النفسي، بينما يزداد تداخل الواقع بالهلوسة والخيال. تتحول الكتابة من مجرد وسيلة للتعبير إلى محاولة للنجاة من الجنون، وتغوص البطلة في عالم مظلم مليء بالأسرار والرعب النفسي، لتواجه مخاوفها وأعماق عقلها في صراع يجعل القارئ يتساءل باستمرار: ما الذي يحدث حقًا، وما الذي هو مجرد وهم؟','https://i.ibb.co/0NGxPCF/f937da8ea10c85b9b45829be297ebded.jpg',1300,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"رواية رعب نفسي وغموض للكاتبة مريم الحيسي، وتمثل الجزء الثاني من سلسلة «أكتب حتى لا يأكلني الشيطان»، لذا يُفضَّل قراءة الجزء الأول قبلها لفهم الشخصيات والخلفية بشكل كامل. \nتتابع الرواية رحلة ماريان بعد الأحداث السابقة، حيث تجد نفسها على حافة الانهيار النفسي، بينما يزداد تداخل الواقع بالهلوسة والخيال. تتحول الكتابة من مجرد وسيلة للتعبير إلى محاولة للنجاة من الجنون، وتغوص البطلة في عالم مظلم مليء بالأسرار والرعب النفسي، لتواجه مخاوفها وأعماق عقلها في صراع يجعل القارئ يتساءل باستمرار: ما الذي يحدث حقًا، وما الذي هو مجرد وهم؟","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK021","img":"https://i.ibb.co/0NGxPCF/f937da8ea10c85b9b45829be297ebded.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1300,"stock_quantity":10,"title":"أكتب حتى لا أصاب بالجنون"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK022','BK022','روايات','أكتب حتى لا أنكسر','الجزء الثالث من سلسلة «الكاتبة للشيطان» للكاتبة مريم الحيسي، وتواصل أحداث الجزأين السابقين: «أكتب حتى لا يأكلني الشيطان» و«أكتب حتى لا أصاب بالجنون». تمزج الرواية بين الرعب النفسي، والغموض، والتشويق، مع لمسات من الفانتازيا والرومانسية المظلمة.
تدور الأحداث حول ماريان التي تجد نفسها على حافة الانهيار بعد اكتشاف أسرار صادمة عن العالم الذي تعيش فيه، إلى جانب حقائق خفية تتعلق بوالدتها سارة. وفي الوقت نفسه، تواجه تهديدًا متزايدًا من ويليام (الملك ديموس)، لتتحول الكتابة من مجرد وسيلة للتنفيس إلى سلاحها الوحيد للنجاة من الخوف والجنون. ومع تصاعد الأحداث، تتشابك الحقيقة مع الوهم، وتزداد الأجواء قتامة وتشويقًا.','https://i.ibb.co/pBDT4pY9/8e0f87b7385e03b96ad17a52caa892e2.jpg',1200,10,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"الجزء الثالث من سلسلة «الكاتبة للشيطان» للكاتبة مريم الحيسي، وتواصل أحداث الجزأين السابقين: «أكتب حتى لا يأكلني الشيطان» و«أكتب حتى لا أصاب بالجنون». تمزج الرواية بين الرعب النفسي، والغموض، والتشويق، مع لمسات من الفانتازيا والرومانسية المظلمة. \nتدور الأحداث حول ماريان التي تجد نفسها على حافة الانهيار بعد اكتشاف أسرار صادمة عن العالم الذي تعيش فيه، إلى جانب حقائق خفية تتعلق بوالدتها سارة. وفي الوقت نفسه، تواجه تهديدًا متزايدًا من ويليام (الملك ديموس)، لتتحول الكتابة من مجرد وسيلة للتنفيس إلى سلاحها الوحيد للنجاة من الخوف والجنون. ومع تصاعد الأحداث، تتشابك الحقيقة مع الوهم، وتزداد الأجواء قتامة وتشويقًا.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK022","img":"https://i.ibb.co/pBDT4pY9/8e0f87b7385e03b96ad17a52caa892e2.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1200,"stock_quantity":10,"title":"أكتب حتى لا أنكسر"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
INSERT INTO "products" VALUES('BK023','BK023','روايات','أكتب حتى لا يأكلني الشيطان','تدور أحداث الرواية حول ماريانا، وهي كاتبة روايات رعب ناجحة، تنقلب حياتها رأسًا على عقب عندما تُختطف على يد شخصية غامضة تُعرف باسم «الشيطان». يفرض عليها الخاطف تحديًا مرعبًا: أن تكتب له باستمرار قصص رعب ترضيه، وإلا سيكون مصيرها الموت كما حدث لعدد من الكتّاب قبله. ومع مرور الوقت، تتحول الكتابة من مهنة إلى وسيلة للبقاء، بينما تبدأ الحدود بين الحقيقة والخيال في التلاشي، وتنكشف أسرار تجعل ماريانا تشك في كل ما حولها.','https://i.ibb.co/kggx5dx8/ab75e9d3-69e1-42a6-b582-0c8010ae55cd.jpg',1500,1,'in_stock',0,0,0,1,0,1,1,0,'{"active":true,"availability_type":"in_stock","category":"روايات","desc":"تدور أحداث الرواية حول ماريانا، وهي كاتبة روايات رعب ناجحة، تنقلب حياتها رأسًا على عقب عندما تُختطف على يد شخصية غامضة تُعرف باسم «الشيطان». يفرض عليها الخاطف تحديًا مرعبًا: أن تكتب له باستمرار قصص رعب ترضيه، وإلا سيكون مصيرها الموت كما حدث لعدد من الكتّاب قبله. ومع مرور الوقت، تتحول الكتابة من مهنة إلى وسيلة للبقاء، بينما تبدأ الحدود بين الحقيقة والخيال في التلاشي، وتنكشف أسرار تجعل ماريانا تشك في كل ما حولها.","discoverable":true,"discovery_tags":[],"featured":false,"gift_tags":[],"giftable":true,"id":"BK023","img":"https://i.ibb.co/kggx5dx8/ab75e9d3-69e1-42a6-b582-0c8010ae55cd.jpg","lead_time_days":0,"lead_time_max_days":0,"lead_time_min_days":0,"price":1500,"stock_quantity":1,"title":"أكتب حتى لا يأكلني الشيطان"}',1,'2026-08-19 23:26:29','2026-08-19 23:26:29');
CREATE TABLE store_settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "store_settings" VALUES('legacy_settings','{"features":{"community":false,"dark_mode":false,"discovery":true,"gift_finder":true,"gift_from_cart":true,"gift_from_product":true,"gifts":true,"ideas_lab":true,"on_demand":true,"smart_search":false}}','2026-08-19 23:26:29');
CREATE UNIQUE INDEX idx_products_category_title ON products(category_slug, title);
CREATE INDEX idx_products_active_featured ON products(active, archived, featured);
CREATE INDEX idx_products_availability ON products(availability_type, active, archived);
CREATE INDEX idx_product_tags_lookup ON product_tags(tag_type, tag);
CREATE INDEX idx_orders_status_created ON orders(status, created_at);
CREATE INDEX idx_orders_phone ON orders(phone);
CREATE INDEX idx_order_items_order ON order_items(order_id, line_number);
CREATE INDEX idx_order_items_product ON order_items(product_id);
CREATE INDEX idx_images_product_active ON image_assets(product_id, archived);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('order_items',14);
COMMIT;
